
const char* const BASE_RGB_SHADER =
"#shader vertex													\n"
"#version 410 core												\n"
"																\n"
"layout(location = 0) in vec4 position;							\n"
"layout(location = 1) in vec2 texCoord;							\n"
"																\n"
"out vec2 v_TexCoord;											\n"
"																\n"
"uniform mat4 u_MVP;											\n"
"																\n"
"void main()													\n"
"{																\n"
"	gl_Position = u_MVP * position;								\n"
"	v_TexCoord = texCoord;										\n"
"};																\n"
"																\n"
"																\n"
"																\n"
"#shader fragment												\n"
"#version 410 core												\n"
"																\n"
"layout(location = 0) out vec4 color;							\n"
"																\n"
"in vec2 v_TexCoord;											\n"
"																\n"
"uniform sampler2D u_Texture;									\n"
"																\n"
"void main()													\n"
"{																\n"
"	vec4 texCoord = texture(u_Texture, v_TexCoord);				\n"
"	color = vec4(texCoord.rgb, 1.0f);							\n"
"};																\n";